pipeline {
    agent any
 
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from your repository
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Use Maven to compile and package the code
                sh 'mvn clean install'
            }
        }
        
        stage('Test') {
            steps {
                // Run unit tests
                sh 'mvn test'
            }
        }
        
        stage('Package') {
            steps {
                // Package the application (optional)
                sh 'mvn package'
            }
        }
    }
 
    post {
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
